version: '3'
networks:
  app-tier:
    driver: bridge
services:
  todoapidocker:
    build: .
    networks:
      - app-tier
    ports:
      - '8080:8080'
    depends_on:
      - pgsqldb
    volumes:
      - './:/usr/src/app'
  pgsqldb:
    image: 'postgres:16.1-alpine'
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier